"""
Oklahoma Supplementary Data | Cannabis Data Science Meetup

Author: Keegan Skeate <keegan@cannlytics.com>
Created: 9/1/2021
Updated: 9/1/2021
License: MIT License
"""

counties = [
    {'name': 'Adair', 'pop_ref': 'OKADAI1POP'},
    {'name': 'Alfalfa', 'pop_ref': 'OKALFA3POP'},
    {'name': 'Atoka', 'pop_ref': 'OKATOK5POP'},
    {'name': 'Beaver', 'pop_ref': 'OKBEAV7POP'},
    {'name': 'Beckham', 'pop_ref': 'OKBECK9POP'},
    {'name': 'Blaine', 'pop_ref': 'OKBLAI1POP'},
    {'name': 'Bryan', 'pop_ref': 'OKBRYA3POP'},
    {'name': 'Caddo', 'pop_ref': 'OKCADD5POP'},
    {'name': 'Canadian', 'pop_ref': 'OKCANA7POP'},
    {'name': 'Carter', 'pop_ref': 'OKCART9POP'},
    {'name': 'Cherokee', 'pop_ref': 'OKCHER1POP'},
    {'name': 'Choctaw', 'pop_ref': 'OKCHOC3POP'},
    {'name': 'Cimarron', 'pop_ref': 'OKCIMA5POP'},
    {'name': 'Cleveland', 'pop_ref': 'OKCLEV7POP'},
    {'name': 'Coal', 'pop_ref': 'OKCOAL9POP'},
    {'name': 'Comanche', 'pop_ref': 'OKCOMA2POP'},
    {'name': 'Cotton', 'pop_ref': 'OKCOTT3POP'},
    {'name': 'Craig', 'pop_ref': 'OKCRAI5POP'},
    {'name': 'Creek', 'pop_ref': 'OKCREE5POP'},
    {'name': 'Custer', 'pop_ref': 'OKCUST9POP'},
    {'name': 'Delaware', 'pop_ref': 'OKDELA1POP'},
    {'name': 'Dewey', 'pop_ref': 'OKDEWE3POP'},
    {'name': 'Ellis', 'pop_ref': 'OKELLI5POP'},
    {'name': 'Garfield', 'pop_ref': 'OKGARF7POP'},
    {'name': 'Garvin', 'pop_ref': 'OKGARV9POP'},
    {'name': 'Grady', 'pop_ref': 'OKGRAD1POP'},
    {'name': 'Grant', 'pop_ref': 'OKGRAN3POP'},
    {'name': 'Greer', 'pop_ref': 'OKGREE5POP'},
    {'name': 'Harmon', 'pop_ref': 'OKHARM7POP'},
    {'name': 'Harper', 'pop_ref': 'OKHARP9POP'},
    {'name': 'Haskell', 'pop_ref': 'OKHASK1POP'},
    {'name': 'Hughes', 'pop_ref': 'OKHUGH3POP'},
    {'name': 'Jackson', 'pop_ref': 'OKJACK5POP'},
    {'name': 'Jefferson', 'pop_ref': 'OKJEFF7POP'},
    {'name': 'Johnston', 'pop_ref': 'OKJOHN9POP'},
    {'name': 'Kay', 'pop_ref': 'OKKAYC1POP'},
    {'name': 'Kingfisher', 'pop_ref': 'OKKING3POP'},
    {'name': 'Kiowa', 'pop_ref': 'OKKIOW5POP'},
    {'name': 'Latimer', 'pop_ref': 'OKLATI7POP'},
    {'name': 'Le Flore', 'pop_ref': 'OKLEFL9POP'},
    {'name': 'Lincoln', 'pop_ref': 'OKLINC1POP'},
    {'name': 'Logan', 'pop_ref': 'OKLOGA3POP'},
    {'name': 'Love', 'pop_ref': 'OKLOVE5POP'},
    {'name': 'Major', 'pop_ref': 'OKMAJO3POP'},
    {'name': 'Marshall', 'pop_ref': 'OKMARS5POP'},
    {'name': 'Mayes', 'pop_ref': 'OKMAYE7POP'},
    {'name': 'McClain', 'pop_ref': 'OKMCCL7POP'},
    {'name': 'McCurtain', 'pop_ref': 'OKMCCU9POP'},
    {'name': 'McIntosh', 'pop_ref': 'OKMCIN1POP'},
    {'name': 'Murray', 'pop_ref': 'OKMURR9POP'},
    {'name': 'Muskogee', 'pop_ref': 'OKMUSK0POP'},
    {'name': 'Noble', 'pop_ref': 'OKNOBL3POP'},
    {'name': 'Nowata', 'pop_ref': 'OKNOWA5POP'},
    {'name': 'Okfuskee', 'pop_ref': 'OKOKFU7POP'},
    {'name': 'Oklahoma', 'pop_ref': 'OKOKLA9POP'},
    {'name': 'Okmulgee', 'pop_ref': 'OKOKMU1POP'},
    {'name': 'Osage', 'pop_ref': 'OKOSAG3POP'},
    {'name': 'Ottawa', 'pop_ref': 'OKOTTA5POP'},
    {'name': 'Pawnee', 'pop_ref': 'OKPAWN7POP'},
    {'name': 'Payne', 'pop_ref': 'OKPAYN0POP'},
    {'name': 'Pittsburg', 'pop_ref': 'OKPITT1POP'},
    {'name': 'Pontotoc', 'pop_ref': 'OKPONT3POP'},
    {'name': 'Pottawatomie', 'pop_ref': 'OKPOTT0POP'},
    {'name': 'Pushmataha', 'pop_ref': 'OKPUSH7POP'},
    {'name': 'Roger Mills', 'pop_ref': 'OKROGE9POP'},
    {'name': 'Rogers', 'pop_ref': 'OKROGE1POP'},
    {'name': 'Seminole', 'pop_ref': 'OKSEMI3POP'},
    {'name': 'Sequoyah', 'pop_ref': 'OKSEQU5POP'},
    {'name': 'Stephens', 'pop_ref': 'OKSTEP7POP'},
    {'name': 'Texas', 'pop_ref': 'OKTEXA9POP'},
    {'name': 'Tillman', 'pop_ref': 'OKTILL1POP'},
    {'name': 'Tulsa', 'pop_ref': 'OKTULS3POP'},
    {'name': 'Wagoner', 'pop_ref': 'OKWAGO5POP'},
    {'name': 'Washington', 'pop_ref': 'OKWASH7POP'},
    {'name': 'Washita', 'pop_ref': 'OKWASH9POP'},
    {'name': 'Woods', 'pop_ref': 'OKWOOD1POP'},
    {'name': 'Woodward', 'pop_ref': 'OKWOOD3POP'},
]